Update sysdig.yml

diff --git a/.github/workflows/sysdig.yml b/.github/workflows/sysdig.yml
--- a/.github/workflows/sysdig.yml
+++ b/.github/workflows/sysdig.yml
@@ -25,8 +25,13 @@ jobs:
     - name: Download sysdig-cli-scanner
       run: |
         curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"  > /usr/local/bin/sysdig-cli-scanner
-        chmod +x /usr/local/bin/sysdig-cli-scanner
-        sysdig-cli-scanner --help
+        sudo chmod +x /usr/local/bin/sysdig-cli-scanner
+        echo $?  # Print exit code
+        ls -al /usr/local/bin
+        cat /usr/local/bin/sysdig-cli-scanner | head -n 20  # Print first 20 lines of the downloaded file
+
+        ls -al /usr/local/bin/sysdig-cli-scanner  # List file details
+        echo "/usr/local/bin" >> $GITHUB_PATH
     - name: Build images
       run: |
         cd original-repo/vote
